version: '3.8'

services:
  frontend:
    container_name: task-manager-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map port 8080 host với port 8080 container
    environment:
      - NODE_ENV=production
    restart: unless-stopped